// DOM simulation checks. These verify rendering and actions, not browser layout.
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');const root=require('node:path').resolve(__dirname,'..');
const hooks={},nodes={},downloads=[],values=new Map();let pendingBlob;
class Element{constructor(){this.innerHTML='';this.textContent='';this.value='';this.dataset={};this.open=false;this.classList={add(){},remove(){}};this.events={};}addEventListener(k,f){this.events[k]=f;}showModal(){this.open=true;}close(){this.open=false;}querySelector(){return null;}querySelectorAll(){return [];}append(){}remove(){}click(){if(this.download)downloads.push({name:this.download,blob:pendingBlob});}getBoundingClientRect(){return {left:0,right:700,top:0,bottom:700};}}
const node=id=>nodes[id]??=(new Element());
class LocalFormData{constructor(f){this.data=f.data||{};}get(k){const x=this.data[k];return x===undefined?null:Array.isArray(x)?x[0]??null:x;}getAll(k){const x=this.data[k];return x===undefined?[]:Array.isArray(x)?x:[x];}has(k){return k in this.data;}}
class URL2 extends URL{}URL2.createObjectURL=b=>{pendingBlob=b;return'blob:local';};URL2.revokeObjectURL=()=>{};
const c={console,URL:URL2,Blob,FormData:LocalFormData,setTimeout:f=>{return 1;},clearTimeout(){},localStorage:{getItem:k=>values.get(k)||null,setItem:(k,v)=>values.set(k,v),removeItem:k=>values.delete(k)},document:{getElementById:node,addEventListener:(k,f)=>hooks[k]=f,querySelector:()=>node('brand'),querySelectorAll:()=>[],createElement:()=>new Element(),createTextNode:t=>({textContent:t}),body:new Element()},fetch:async()=>({text:async()=>fs.readFileSync(root+'/style.css','utf8')})};c.window=c;c.print=()=>{};vm.createContext(c);for(const f of ['data.js','store.js','app.js'])vm.runInContext(fs.readFileSync(root+'/'+f,'utf8'),c);
const click=async(action,id='',extra={})=>{const el={dataset:{action,id,...extra},disabled:false};hooks.click({target:{closest:()=>el},preventDefault(){}});await new Promise(resolve=>setImmediate(resolve));};
const html=()=>node('content').innerHTML;
const submit=async(id,data,ds={})=>{await hooks.submit({preventDefault(){},target:{id,data,dataset:ds,querySelector:()=>null}});};
(async()=>{
assert.ok(html().includes('Participants by state'));assert.ok(html().includes('Participants by gender'));assert.ok(html().includes('Class requirement met'));assert.equal((node('nav').innerHTML.match(/data-action="navigate"/g)||[]).length,2);
await click('dimension','Johor',{key:'state'});assert.ok(html().includes('10 participants in scope'));
await click('go-reports');await click('generate-report');assert.ok(html().includes('Programme impact report'));await click('export-csv');let csv=await downloads.at(-1).blob.text();assert.equal(csv.split('\r\n').length,11);assert.ok(csv.includes('Johor'));assert.ok(!csv.includes('Penang'));assert.ok(!csv.includes('private'));
for(const r of ['summary','learning','attendance']){await click('report-type',r);await click('generate-report');assert.ok(html().includes('report-preview'));await click('export-csv');assert.ok(downloads.at(-1).name.includes(r));}
c.MaxisUI.setPreview('participant','EKU-001');await click('open-module','M1');await click('lesson-resource','M1-V');assert.ok(html().includes('<video'));assert.ok(html().includes('Your private notes'));
await click('lesson-resource','quiz');assert.ok(html().includes('quiz-form'));await submit('quiz-form',{q0:'0',q1:'1',q2:'2',q3:'3'},{module:'M1'});assert.ok(html().includes('You passed'));
await click('navigate','business');assert.ok(html().includes('Monthly business records'));await click('checkin','EKU-001');assert.ok(node('dialog-content').innerHTML.includes('Monthly business check-in'));await submit('checkin-form',{month:'2026-10',sales:'4000',cost:'2200',notes:'A good month',story:'My new story',consent:'on'},{id:'EKU-001'});assert.ok(html().includes('October 2026'));assert.ok(html().includes('RM 1,800'));
c.MaxisUI.setPreview('admin','U0');await click('navigate','people');await click('add-person');assert.ok(node('dialog-content').innerHTML.includes('classTarget'));await submit('person-form',{name:'UI Demo',business:'UI Store',programme:'Accelerator',cohort:'01',state:'Selangor',gender:'Female',mentor:'U1',sector:'Retail',email:'ui@example.test',phone:'',age:'25',goal:'Demo',background:'B40',classTarget:'4',baselineSales:'',baselineCost:'',moduleIds:['M1','M2'],access:'on'},{id:''});assert.ok(html().includes('UI Demo'));
await click('navigate','modules');assert.ok(html().includes('Pitch your next chapter'));await click('manage-module','M1');assert.ok(html().includes('Knowledge check'));await click('edit-quiz','M1');assert.ok(node('dialog-content').innerHTML.includes('quiz-editor-form'));
await click('navigate','attendance');assert.ok(html().includes('Whole programme / cohort roster'));assert.ok(html().includes('Finalized'));await click('new-session');assert.ok(node('dialog-content').innerHTML.includes('type="date"'));await submit('session-form',{number:'3',date:'2026-10-09',title:'UI Meeting'});assert.ok(html().includes('Live draft'));const session=c.Maxis.state.sessions.at(-1);for(const id of session.roster)await click('mark-attendance',id,{mark:'present'});await click('finalize-session',session.id);assert.ok(html().includes('Reopen to correct'));assert.equal(c.Maxis.findSession(session.id).finalized,true);
c.MaxisUI.setPreview('stakeholder','U4');await click('go-reports');await click('generate-report');assert.ok(html().includes('Penang'));assert.ok(!html().includes('UI Demo'));await click('export-csv');csv=await downloads.at(-1).blob.text();assert.equal(csv.split('\r\n').length,11);assert.ok(!csv.includes('ui@example.test'));

console.log('PASS UI rendering, role navigation, module/video/quiz flows, enrolment, check-ins, attendance finalization and scoped report exports.');
})().catch(e=>{console.error(e);process.exitCode=1});
