// Dependency-free integration tests for the shared prototype service layer.
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const dir=path.resolve(__dirname,'..');const values=new Map();let failStorage=false;
function load(){const c={window:{},localStorage:{getItem:k=>values.get(k)||null,setItem:(k,v)=>{if(failStorage)throw new Error('storage full');values.set(k,v)},removeItem:k=>values.delete(k)},URL,console};c.window=c;vm.createContext(c);for(const file of ['data.js','store.js'])vm.runInContext(fs.readFileSync(path.join(dir,file),'utf8'),c);return c.Maxis;}
let S=load();const admin=S.actor('admin','U0'),stake=S.actor('stakeholder','U3'),regional=S.actor('stakeholder','U4'),mentor=S.actor('mentor','U1');let passed=0;
function test(name,fn){fn();passed++;console.log('PASS '+name);}
const input=(name='Demo Learner')=>({name,business:'Demo Shop',programme:'Accelerator',cohort:'01',state:'Selangor',gender:'Female',mentor:'U1',classTarget:2,email:'',phone:'',sector:'Retail',background:'B40',age:30,goal:'Learn practical skills',moduleIds:['M1','M2'],access:true,baseline:null});
let pid,a,mid,sid;
test('Seed data, scoped state/gender analytics and matched income samples',()=>{assert.equal(S.stats(stake).count,30);assert.equal(S.stats(regional).count,10);assert.equal(S.stats(stake,{state:'Johor'}).count,10);assert.equal(S.stats(stake,{gender:'Female'}).count,20);assert.equal(S.stats(stake,{month:'2026-09'}).reporting,25);assert.equal(S.filtered(regional,{cohort:'01'}).length,0);assert.ok(S.stats(stake).moduleTotal>S.stats(stake).moduleDone);});
test('Admin enrolment creates a blank learning and business record',()=>{pid=S.savePerson(admin,input());a=S.actor('participant',pid);const p=S.findPerson(pid);assert.equal(p.checkins.length,0);assert.equal(p.photo,'');assert.equal(S.pathway(p).done,0);assert.equal(S.stats(stake,{month:'2026-09'}).reporting,25);assert.equal(S.attendance(p).total,0);});
test('Stakeholders and mentors cannot enrol or administer content',()=>{assert.throws(()=>S.savePerson(stake,input()),/admins/);assert.throws(()=>S.savePerson(mentor,input()),/admins/);assert.throws(()=>S.saveModule(stake,{title:'x'}),/admins/);assert.throws(()=>S.markResource(stake,'M1','M1-R'),/participant/);});
test('Unassigned content and incomplete resources block quizzes',()=>{assert.throws(()=>S.markResource(a,'M3','M3-R'),/assigned/);assert.throws(()=>S.submitQuiz(a,'M1',[0,1,2,3]),/Study/);});
test('Resources, private notes and quiz fail/retry/pass update the same ledger',()=>{const m=S.findModule('M1');m.resources.forEach(r=>S.markResource(a,m.id,r.id));S.saveNote(a,'M1','M1-R','My private customer notes');const first=S.submitQuiz(a,'M1',[3,3,3,0]);assert.equal(first.passed,false);assert.equal(S.progress(S.findPerson(pid),m).complete,false);const before=S.stats(stake).moduleDone;const next=S.submitQuiz(a,'M1',m.quiz.map(q=>q.correct));assert.equal(next.score,100);assert.equal(S.progress(S.findPerson(pid),m).complete,true);assert.equal(S.stats(stake).moduleDone,before+1);S.submitQuiz(a,'M1',[3,3,3,0]);assert.equal(S.progress(S.findPerson(pid),m).complete,true);assert.equal(S.record(S.findPerson(pid),m).notes['M1-R'],'My private customer notes');});
test('Quiz answers must be complete and within range',()=>{assert.throws(()=>S.submitQuiz(a,'M1',[0]),/every/);assert.throws(()=>S.submitQuiz(a,'M1',[0,1,2,9]),/every/);});
test('Module creation, publishing gates, assignments and revisions',()=>{mid=S.saveModule(admin,{title:'Demo module',description:'Test learning content',programmes:['Accelerator'],duration:10,passMark:70});assert.throws(()=>S.setPublished(admin,mid,true),/resource/);S.saveResource(admin,mid,{title:'Reading',type:'reading',body:'Study this content.'});S.saveQuiz(admin,mid,[{prompt:'Choose A',options:['A','B','C','D'],correct:0,explanation:'A is correct.'}]);S.setPublished(admin,mid,true);assert.equal(S.available(S.findPerson(pid)).some(m=>m.id===mid),false);const inp={...input(),moduleIds:['M1','M2',mid]};S.savePerson(admin,inp,pid);assert.equal(S.available(S.findPerson(pid)).some(m=>m.id===mid),true);const m=S.findModule(mid);S.markResource(a,mid,m.resources[0].id);S.submitQuiz(a,mid,[0]);assert.equal(S.progress(S.findPerson(pid),m).complete,true);S.saveResource(admin,mid,{title:'Second reading',type:'reading',body:'Another lesson.'});assert.equal(S.progress(S.findPerson(pid),m).complete,false);assert.throws(()=>S.saveResource(admin,mid,{title:'Bad video',type:'video',url:'javascript:alert(1)'}),/HTTPS/);S.saveModule(admin,{title:m.title,description:m.description,programmes:m.programmes,duration:10,passMark:90},mid);assert.equal(S.findModule(mid).passMark,90);});
test('Participant business data is own-only and always self-reported',()=>{S.saveCheckin(a,pid,{month:'2026-10',sales:3500,cost:1800,notes:'New check-in',story:'Example story',consent:true,milestone:true,reviewed:true});assert.equal(S.findPerson(pid).checkins[0].reviewed,false);assert.equal(S.stats(stake,{month:'2026-10'}).average,1700);assert.equal(S.stats(stake,{month:'2026-10'}).growth,null);assert.throws(()=>S.saveCheckin(a,'EKU-002',{month:'2026-10',sales:1,cost:0}),/cannot/);assert.throws(()=>S.saveCheckin(a,pid,{month:'2026-10',sales:-1,cost:0}),/nonnegative/);});
test('Meeting duplicates open existing records and live marks link to profiles',()=>{sid=S.createSession(mentor,{programme:'Accelerator',cohort:'01',number:3,date:'2026-10-09',title:'Practice clinic'});assert.equal(S.createSession(mentor,{programme:'Accelerator',cohort:'01',number:3,date:'2026-10-10',title:'Duplicate'}),sid);assert.throws(()=>S.finalizeSession(mentor,sid),/Mark everyone/);S.markAttendance(mentor,sid,pid,'present');assert.equal(S.findSession(sid).marks[pid],'present');assert.equal(S.attendance(S.findPerson(pid)).total,0);S.sessionRoster(S.findSession(sid)).forEach(p=>S.markAttendance(mentor,sid,p.id,'present'));S.finalizeSession(mentor,sid);assert.equal(S.attendance(S.findPerson(pid)).present,1);assert.equal(S.classProgress(S.findPerson(pid)).complete,false);assert.throws(()=>S.markAttendance(stake,sid,pid,'absent'),/No access/);assert.throws(()=>S.markAttendance(mentor,sid,pid,'absent'),/Reopen/);});
test('Finalized rosters stay historical after corrections and later enrolment',()=>{const second=S.savePerson(admin,input('Later learner'));assert.equal(S.sessionRoster(S.findSession(sid)).some(p=>p.id===second),false);S.reopenSession(mentor,sid);assert.equal(S.attendance(S.findPerson(pid)).total,0);assert.equal(S.sessionRoster(S.findSession(sid)).some(p=>p.id===second),false);S.markAttendance(mentor,sid,pid,'absent');S.finalizeSession(mentor,sid);assert.equal(S.attendance(S.findPerson(pid)).present,0);assert.equal(S.attendance(S.findPerson(second)).total,0);});
test('Draft rosters include newly enrolled participants and class targets use finalized presence',()=>{const s2=S.createSession(mentor,{programme:'Accelerator',cohort:'01',number:4,date:'2026-10-10',title:'Fourth session'});const newId=S.savePerson(admin,input('Newest learner'));assert.equal(S.sessionRoster(S.findSession(s2)).some(p=>p.id===newId),true);S.sessionRoster(S.findSession(s2)).forEach(p=>S.markAttendance(mentor,s2,p.id,'present'));S.finalizeSession(mentor,s2);assert.equal(S.attendance(S.findPerson(pid)).present,1);const s3=S.createSession(mentor,{programme:'Accelerator',cohort:'01',number:5,date:'2026-10-11',title:'Fifth session'});S.sessionRoster(S.findSession(s3)).forEach(p=>S.markAttendance(mentor,s3,p.id,'present'));S.finalizeSession(mentor,s3);assert.equal(S.classProgress(S.findPerson(pid)).complete,true);assert.equal(S.attendance(S.findPerson(pid),'2026-09-30').total,0);});
test('Disabled participant access and cohort restrictions take effect',()=>{S.savePerson(admin,{...input(),access:false},pid);assert.throws(()=>S.actor('participant',pid),/disabled/);assert.throws(()=>S.createSession(mentor,{programme:'Accelerator',cohort:'03',number:3,date:'2026-10-09'}),/No access/);assert.throws(()=>S.saveUser(admin,{name:'Aina',role:'mentor',cohorts:['01'],active:true},'U1'),/Reassign/);S.savePerson(admin,input(),pid);});
test('Photos require own or admin access; malformed data is rejected',()=>{assert.throws(()=>S.setPhoto(stake,pid,''),/access/);assert.throws(()=>S.setPhoto(a,pid,'https://image.example'),/Unsupported/);S.setPhoto(a,pid,'data:image/jpeg;base64,ZmFrZQ==');assert.ok(S.findPerson(pid).photo.startsWith('data:'));S.setPhoto(a,pid,'');});
test('Failed storage writes roll back, including analytics',()=>{const before=JSON.stringify(S.state);failStorage=true;assert.throws(()=>S.savePerson(admin,input('Cannot save')),/storage full/);assert.equal(JSON.stringify(S.state),before);failStorage=false;});
test('Reload retains edits and reset restores demo without deleting earlier versions',()=>{S=load();assert.ok(S.findPerson(pid));assert.equal(S.stats(S.actor('stakeholder','U3')).count,33);values.set('maxis-impact-prototype-v2','previous version');S.reset();assert.equal(S.state.people.length,30);assert.equal(values.get('maxis-impact-prototype-v2'),'previous version');});
console.log(`\n${passed} integration checks passed.`);
